import { randomUUID } from "node:crypto";
import { copyFile, lstat, mkdir, readFile, readdir, realpath, rename, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from "node:path";
import { z } from "zod";
import type { WorkspaceRecord } from "./database";
import { DomainError } from "./workspaces";

const rootSchema = z.object({ id: z.uuid(), workspaceId: z.uuid(), name: z.string(), path: z.string(), createdAt: z.iso.datetime() }).strict();
const actionSchema = z.object({ id: z.uuid(), workspaceId: z.uuid(), kind: z.enum(["file", "native"]), operation: z.string(), rootId: z.uuid().nullable(), source: z.string().nullable(), destination: z.string().nullable(), content: z.string().nullable(), target: z.record(z.string(), z.unknown()).nullable(), state: z.enum(["awaiting-approval", "queued", "running", "completed", "failed", "interrupted", "undone"]), result: z.record(z.string(), z.unknown()).nullable(), error: z.string().nullable(), undo: z.record(z.string(), z.unknown()).nullable(), createdAt: z.iso.datetime(), updatedAt: z.iso.datetime() }).strict();
const registrySchema = z.object({ schemaVersion: z.literal(1), roots: z.array(rootSchema), actions: z.array(actionSchema) }).strict();
type Registry = z.infer<typeof registrySchema>; type Root = z.infer<typeof rootSchema>; type Action = z.infer<typeof actionSchema>;

async function atomicWrite(path: string, value: unknown) { const temporary = `${path}.tmp-${randomUUID()}`; await mkdir(dirname(path), { recursive: true }); await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { flag: "wx" }); try { await rename(temporary, path); } catch (error) { await rm(temporary, { force: true }); throw error; } }
function contains(parent: string, child: string) { const value = relative(parent, child); return value === "" || (!value.startsWith(`..${sep}`) && value !== ".." && !isAbsolute(value)); }
function normalizeRelative(value: string) { const normalized = posix.normalize(value.replaceAll("\\", "/")).replace(/^\.\//, ""); if (!normalized || normalized === "." || isAbsolute(normalized) || normalized === ".." || normalized.startsWith("../") || normalized.startsWith(".voidra/")) throw new DomainError("WORKSPACE_CONFLICT", "The file action path escapes its selected root."); return normalized; }

export class AutomationManager {
  readonly #registries = new Map<string, Registry>(); readonly #saveQueues = new Map<string, Promise<void>>();
  constructor(private readonly hostCall?: (operation: "native.status" | "native.action" | "native.takeover", workspaceId: string, actionId: string, payload: Record<string, unknown>) => Promise<unknown>) {}

  async list(workspace: WorkspaceRecord) { const registry = await this.#registry(workspace); return { roots: registry.roots, actions: [...registry.actions].sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }; }
  async addRoot(workspace: WorkspaceRecord, name: string, path: string) { const canonical = await realpath(path); if (!(await stat(canonical)).isDirectory()) throw new DomainError("WORKSPACE_CONFLICT", "The selected automation root is not a directory."); const registry = await this.#registry(workspace); if (registry.roots.some((root) => root.path === canonical)) throw new DomainError("WORKSPACE_CONFLICT", "This folder is already selected in the workspace."); const root: Root = { id: randomUUID(), workspaceId: workspace.id, name: name.trim(), path: canonical, createdAt: new Date().toISOString() }; registry.roots.push(root); await this.#save(workspace, registry); return root; }
  async removeRoot(workspace: WorkspaceRecord, rootId: string) { const registry = await this.#registry(workspace); const index = registry.roots.findIndex((root) => root.id === rootId && root.workspaceId === workspace.id); if (index < 0) throw new DomainError("WORKSPACE_CONFLICT", "The selected file root does not belong to this workspace."); registry.roots.splice(index, 1); await this.#save(workspace, registry); return { removed: true }; }

  async listFiles(workspace: WorkspaceRecord, rootId: string, path: string) { const registry = await this.#registry(workspace); const root = this.#root(registry, workspace.id, rootId); await this.#validateRoot(root); const directory = path ? await this.#source(root, path, true) : root.path; const entries = await readdir(directory, { withFileTypes: true }); return { root, path, entries: entries.filter((entry) => !entry.isSymbolicLink()).map((entry) => ({ name: entry.name, path: path ? `${path}/${entry.name}` : entry.name, type: entry.isDirectory() ? "directory" : "file" })).sort((a, b) => a.name.localeCompare(b.name)) }; }

  async prepareFile(workspace: WorkspaceRecord, input: { rootId: string; action: "copy" | "move" | "trash" | "write"; source: string; destination?: string; content?: string }) {
    const registry = await this.#registry(workspace); const root = this.#root(registry, workspace.id, input.rootId); await this.#validateRoot(root); const source = normalizeRelative(input.source);
    if (input.action !== "write") await this.#source(root, source, false); else await this.#destination(root, source);
    if ((input.action === "copy" || input.action === "move") && !input.destination) throw new DomainError("AUTOMATION_STATE_CONFLICT", "Copy and move require an exact destination.");
    if (input.destination) await this.#destination(root, normalizeRelative(input.destination));
    const now = new Date().toISOString(); const action: Action = { id: randomUUID(), workspaceId: workspace.id, kind: "file", operation: input.action, rootId: root.id, source, destination: input.destination ? normalizeRelative(input.destination) : null, content: input.action === "write" ? input.content ?? "" : null, target: null, state: "awaiting-approval", result: null, error: null, undo: null, createdAt: now, updatedAt: now }; registry.actions.push(action); await this.#save(workspace, registry); return action;
  }

  async approveFile(workspace: WorkspaceRecord, actionId: string) {
    const registry = await this.#registry(workspace); const action = this.#action(registry, workspace.id, actionId, "file"); if (action.state !== "awaiting-approval") throw new DomainError("AUTOMATION_STATE_CONFLICT", "This file action is no longer awaiting approval."); const root = this.#root(registry, workspace.id, action.rootId!); action.state = "running"; action.updatedAt = new Date().toISOString(); await this.#save(workspace, registry);
    try {
      if (action.operation === "copy") { const source = await this.#source(root, action.source!, false); const destination = await this.#destination(root, action.destination!); await mkdir(dirname(destination), { recursive: true }); await copyFile(source, destination, 1); action.undo = { operation: "remove-copy", path: action.destination! }; action.result = { source: action.source, destination: action.destination }; }
      else if (action.operation === "move") { const source = await this.#source(root, action.source!, false); const destination = await this.#destination(root, action.destination!); await mkdir(dirname(destination), { recursive: true }); await rename(source, destination); action.undo = { operation: "move-back", source: action.destination!, destination: action.source! }; action.result = { source: action.source, destination: action.destination }; }
      else if (action.operation === "trash") { const source = await this.#source(root, action.source!, false); const trashDirectory = join(workspace.canonicalPath, ".voidra", "automation-trash", action.id); await mkdir(trashDirectory, { recursive: true }); const destination = join(trashDirectory, basename(source)); await rename(source, destination); action.undo = { operation: "restore-trash", source: destination, destination: source }; action.result = { source: action.source, recoverable: true }; }
      else { const destination = await this.#destination(root, action.source!); let previous: string | null = null; try { previous = await readFile(destination, "utf8"); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } await mkdir(dirname(destination), { recursive: true }); await writeFile(destination, action.content ?? "", { flag: previous === null ? "wx" : "w" }); action.undo = previous === null ? { operation: "remove-write", path: action.source! } : { operation: "restore-write", path: action.source!, content: previous }; action.result = { path: action.source, bytes: Buffer.byteLength(action.content ?? "") }; }
      action.state = "completed";
    } catch (error) { action.state = "failed"; action.error = error instanceof Error ? error.message : "The file action failed."; }
    action.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return action;
  }

  async undoFile(workspace: WorkspaceRecord, actionId: string) { const registry = await this.#registry(workspace); const action = this.#action(registry, workspace.id, actionId, "file"); if (action.state !== "completed" || !action.undo) throw new DomainError("AUTOMATION_STATE_CONFLICT", "This action has no available undo."); const root = this.#root(registry, workspace.id, action.rootId!); const undo = action.undo; const operation = String(undo.operation); if (operation === "remove-copy" || operation === "remove-write") await rm(await this.#source(root, String(undo.path), false)); else if (operation === "move-back") { const source = await this.#source(root, String(undo.source), false); const destination = await this.#destination(root, String(undo.destination)); await mkdir(dirname(destination), { recursive: true }); await rename(source, destination); } else if (operation === "restore-write") await writeFile(await this.#source(root, String(undo.path), false), String(undo.content), "utf8"); else if (operation === "restore-trash") { const source = String(undo.source); const destination = String(undo.destination); if (!contains(join(workspace.canonicalPath, ".voidra", "automation-trash"), source) || !contains(root.path, destination)) throw new DomainError("WORKSPACE_CONFLICT", "The recovery path is no longer valid."); await mkdir(dirname(destination), { recursive: true }); await rename(source, destination); } else throw new DomainError("AUTOMATION_STATE_CONFLICT", "Unknown undo operation."); action.state = "undone"; action.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return action; }

  async capabilities(workspace: WorkspaceRecord) { return this.hostCall ? this.hostCall("native.status", workspace.id, randomUUID(), {}) : { accessibility: "unsupported", screen: "unsupported", automation: "unsupported", adapter: "none" }; }
  async agentCapabilities(workspace: WorkspaceRecord) { const registry = await this.#registry(workspace); return { roots: registry.roots.map(({ id, name, path }) => ({ id, name, path })), native: await this.capabilities(workspace) as Record<string, unknown> }; }
  async executeForAgent(workspace: WorkspaceRecord, input: Record<string, unknown>) { const kind = String(input.kind ?? ""); if (kind === "file") { const prepared = await this.prepareFile(workspace, { rootId: String(input.rootId ?? ""), action: String(input.action ?? "") as "copy" | "move" | "trash" | "write", source: String(input.source ?? ""), destination: typeof input.destination === "string" ? input.destination : undefined, content: typeof input.content === "string" ? input.content : undefined }); return this.approveFile(workspace, prepared.id); } if (kind === "native") { const target = input.target && typeof input.target === "object" && !Array.isArray(input.target) ? input.target as Record<string, unknown> : {}; const prepared = await this.prepareNative(workspace, String(input.operation ?? ""), target); return this.approveNative(workspace, prepared.id); } throw new DomainError("AUTOMATION_STATE_CONFLICT", "Unknown automation action kind."); }
  async prepareNative(workspace: WorkspaceRecord, operation: string, target: Record<string, unknown>) { const registry = await this.#registry(workspace); const now = new Date().toISOString(); const action: Action = { id: randomUUID(), workspaceId: workspace.id, kind: "native", operation, rootId: null, source: null, destination: null, content: null, target, state: "awaiting-approval", result: null, error: null, undo: null, createdAt: now, updatedAt: now }; registry.actions.push(action); await this.#save(workspace, registry); return action; }
  async approveNative(workspace: WorkspaceRecord, actionId: string) { const registry = await this.#registry(workspace); const action = this.#action(registry, workspace.id, actionId, "native"); if (action.state !== "awaiting-approval") throw new DomainError("AUTOMATION_STATE_CONFLICT", "This native action is no longer awaiting approval."); if (!this.hostCall) throw new DomainError("AUTOMATION_STATE_CONFLICT", "Native automation is unavailable."); action.state = "queued"; action.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); try { action.result = await this.hostCall("native.action", workspace.id, action.id, { operation: action.operation, target: action.target ?? {} }) as Record<string, unknown>; action.state = action.result.interrupted ? "interrupted" : "completed"; } catch (error) { action.state = "failed"; action.error = error instanceof Error ? error.message : "Native action failed."; } action.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return action; }
  async takeover(workspace: WorkspaceRecord) { if (!this.hostCall) throw new DomainError("AUTOMATION_STATE_CONFLICT", "Native automation is unavailable."); const result = await this.hostCall("native.takeover", workspace.id, randomUUID(), {}); const registry = await this.#registry(workspace); for (const action of registry.actions) if (action.kind === "native" && (action.state === "queued" || action.state === "running")) { action.state = "interrupted"; action.error = "User takeover interrupted desktop control."; action.updatedAt = new Date().toISOString(); } await this.#save(workspace, registry); return result; }

  #root(registry: Registry, workspaceId: string, rootId: string) { const root = registry.roots.find((candidate) => candidate.id === rootId && candidate.workspaceId === workspaceId); if (!root) throw new DomainError("WORKSPACE_CONFLICT", "The selected file root does not belong to this workspace."); return root; }
  async #validateRoot(root: Root) { const details = await lstat(root.path); if (details.isSymbolicLink() || !details.isDirectory() || await realpath(root.path) !== root.path) throw new DomainError("WORKSPACE_CONFLICT", "The selected file root changed or is unavailable."); }
  #action(registry: Registry, workspaceId: string, actionId: string, kind: "file" | "native") { const action = registry.actions.find((candidate) => candidate.id === actionId && candidate.workspaceId === workspaceId && candidate.kind === kind); if (!action) throw new DomainError("WORKSPACE_CONFLICT", "The automation action does not belong to this workspace."); return action; }
  async #source(root: Root, relativePath: string, directory: boolean) { const candidate = resolve(root.path, ...normalizeRelative(relativePath).split("/")); if (!contains(root.path, candidate)) throw new DomainError("WORKSPACE_CONFLICT", "The file action path escapes its selected root."); const details = await lstat(candidate); if (details.isSymbolicLink()) throw new DomainError("WORKSPACE_CONFLICT", "Symbolic links are not allowed in automation actions."); const canonical = await realpath(candidate); if (!contains(root.path, canonical) || (directory ? !details.isDirectory() : !details.isFile())) throw new DomainError("WORKSPACE_CONFLICT", "The selected source is unavailable or outside its root."); return canonical; }
  async #destination(root: Root, relativePath: string) { const candidate = resolve(root.path, ...normalizeRelative(relativePath).split("/")); if (!contains(root.path, candidate)) throw new DomainError("WORKSPACE_CONFLICT", "The destination escapes its selected root."); let ancestor = dirname(candidate); while (true) { try { const details = await lstat(ancestor); if (details.isSymbolicLink()) throw new DomainError("WORKSPACE_CONFLICT", "Symbolic-link destinations are not allowed."); ancestor = await realpath(ancestor); break; } catch (error) { if (error instanceof DomainError) throw error; if ((error as NodeJS.ErrnoException).code !== "ENOENT" || ancestor === root.path) throw error; ancestor = dirname(ancestor); } } if (!contains(root.path, ancestor)) throw new DomainError("WORKSPACE_CONFLICT", "The destination escapes its selected root."); try { await lstat(candidate); throw new DomainError("AUTOMATION_STATE_CONFLICT", "The destination already exists."); } catch (error) { if (error instanceof DomainError) throw error; if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } return candidate; }
  #path(workspace: WorkspaceRecord) { return join(workspace.canonicalPath, ".voidra", "automation.json"); }
  async #registry(workspace: WorkspaceRecord) { const cached = this.#registries.get(workspace.id); if (cached) return cached; let registry: Registry; try { registry = registrySchema.parse(JSON.parse(await readFile(this.#path(workspace), "utf8"))); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new DomainError("INCOMPATIBLE_SCHEMA", "Automation metadata requires recovery."); registry = { schemaVersion: 1, roots: [], actions: [] }; } for (const action of registry.actions) if (action.state === "running" || action.state === "queued") { action.state = "interrupted"; action.error = "The runtime stopped before the desktop action completed."; action.updatedAt = new Date().toISOString(); } this.#registries.set(workspace.id, registry); await this.#save(workspace, registry); return registry; }
  async #save(workspace: WorkspaceRecord, registry: Registry) { const previous = this.#saveQueues.get(workspace.id) ?? Promise.resolve(); const current = previous.catch(() => undefined).then(() => atomicWrite(this.#path(workspace), registry)); this.#saveQueues.set(workspace.id, current); await current; if (this.#saveQueues.get(workspace.id) === current) this.#saveQueues.delete(workspace.id); }
}
