import { randomUUID } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { z } from "zod";
import type { AgentTaskManager } from "./agents";
import type { WorkspaceRecord } from "./database";
import type { WorkspaceManager } from "./workspaces";
import { DomainError } from "./workspaces";
import { isTestRuntime } from "../domain/runtime-mode";

const turnSchema = z.object({ utteranceId: z.uuid(), transcriptId: z.string(), text: z.string(), final: z.boolean(), response: z.string().nullable(), taskId: z.uuid().nullable(), createdAt: z.iso.datetime() }).strict();
const sessionSchema = z.object({ id: z.uuid(), workspaceId: z.uuid(), mode: z.enum(["push-to-talk", "conversation"]), state: z.enum(["idle", "listening", "transcribing", "thinking", "speaking", "interrupted", "error", "muted"]), generation: z.number().int().nonnegative(), activeUtteranceId: z.uuid().nullable(), activeTaskId: z.uuid().nullable(), partial: z.string(), audioBase64: z.string().nullable(), error: z.string().nullable(), turns: z.array(turnSchema), createdAt: z.iso.datetime(), updatedAt: z.iso.datetime() }).strict();
const registrySchema = z.object({ schemaVersion: z.literal(1), wakeWordEnabled: z.boolean(), muted: z.boolean(), retainTranscripts: z.boolean(), seenTranscriptIds: z.array(z.string()), sessions: z.array(sessionSchema) }).strict();
type Registry = z.infer<typeof registrySchema>;
type Session = z.infer<typeof sessionSchema>;
type Turn = z.infer<typeof turnSchema>;

async function atomicWrite(path: string, value: unknown) { const temporary = `${path}.tmp-${randomUUID()}`; await mkdir(dirname(path), { recursive: true }); await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { flag: "wx" }); try { await rename(temporary, path); } catch (error) { await rm(temporary, { force: true }); throw error; } }

export class VoiceManager {
  readonly #registries = new Map<string, Registry>(); readonly #saveQueues = new Map<string, Promise<void>>();
  readonly #speechControllers = new Map<string, AbortController>();
  constructor(private readonly workspaces: WorkspaceManager, private readonly agents: AgentTaskManager, private readonly credential: () => string | null, private readonly fetchImpl: typeof fetch = fetch, private readonly baseUrl = process.env.VOIDRA_ELEVENLABS_BASE_URL ?? "https://api.elevenlabs.io") {}
  async list(workspace: WorkspaceRecord) { const registry = await this.#registry(workspace); return { wakeWordEnabled: registry.wakeWordEnabled, muted: registry.muted, retainTranscripts: registry.retainTranscripts, sessions: registry.sessions.map((session) => registry.retainTranscripts ? session : { ...session, turns: [] }) }; }
  async configure(workspace: WorkspaceRecord, input: { wakeWordEnabled?: boolean; muted?: boolean; retainTranscripts?: boolean }) { const registry = await this.#registry(workspace); if (input.wakeWordEnabled !== undefined) registry.wakeWordEnabled = input.wakeWordEnabled; if (input.muted !== undefined) { registry.muted = input.muted; for (const session of registry.sessions) if (input.muted) { this.#speechControllers.get(session.id)?.abort(); session.state = "muted"; session.generation += 1; session.audioBase64 = null; } else if (session.state === "muted") session.state = "idle"; } if (input.retainTranscripts !== undefined) { registry.retainTranscripts = input.retainTranscripts; if (!input.retainTranscripts) for (const session of registry.sessions) session.turns = []; } await this.#save(workspace, registry); return this.list(workspace); }
  async start(workspace: WorkspaceRecord, mode: "push-to-talk" | "conversation") { const registry = await this.#registry(workspace); const now = new Date().toISOString(); const session: Session = { id: randomUUID(), workspaceId: workspace.id, mode, state: registry.muted ? "muted" : "listening", generation: 0, activeUtteranceId: null, activeTaskId: null, partial: "", audioBase64: null, error: null, turns: [], createdAt: now, updatedAt: now }; registry.sessions.push(session); if (registry.sessions.length > 50) registry.sessions.splice(0, registry.sessions.length - 50); await this.#save(workspace, registry); return session; }
  async partial(workspace: WorkspaceRecord, input: { sessionId: string; utteranceId: string; transcriptId: string; text: string }) { const registry = await this.#registry(workspace); const session = this.#session(registry, workspace.id, input.sessionId); if (registry.muted) throw new DomainError("VOICE_STATE_CONFLICT", "Voice input is muted."); if (registry.seenTranscriptIds.includes(input.transcriptId)) return { ...session, duplicate: true }; session.state = "transcribing"; session.activeUtteranceId = input.utteranceId; session.partial = input.text; session.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return session; }
  async transcribe(workspace: WorkspaceRecord, input: { sessionId: string; utteranceId: string; transcriptId: string; audioBase64: string; mimeType: string }) {
    const registry = await this.#registry(workspace);
    const session = this.#session(registry, workspace.id, input.sessionId);
    if (registry.muted) throw new DomainError("VOICE_STATE_CONFLICT", "Voice input is muted.");
    if (registry.seenTranscriptIds.includes(input.transcriptId)) return { session, transcriptId: input.transcriptId, text: session.partial, duplicate: true };
    const key = this.credential();
    if (!key) throw new DomainError("VOICE_STATE_CONFLICT", "An ElevenLabs credential is required for transcription.");
    session.state = "transcribing";
    session.activeUtteranceId = input.utteranceId;
    session.error = null;
    await this.#save(workspace, registry);
    const form = new FormData();
    const extension = input.mimeType.includes("ogg") ? "ogg" : input.mimeType.includes("mp4") ? "m4a" : "webm";
    form.append("file", new Blob([Buffer.from(input.audioBase64, "base64")], { type: input.mimeType }), `utterance.${extension}`);
    form.append("model_id", "scribe_v2");
    let response: Response;
    try { response = await this.fetchImpl(`${this.baseUrl}/v1/speech-to-text`, { method: "POST", headers: { "xi-api-key": key }, body: form }); }
    catch (error) { session.state = "error"; session.error = error instanceof Error ? error.message : "Transcription failed."; await this.#save(workspace, registry); throw new DomainError("VOICE_STATE_CONFLICT", session.error, true); }
    if (!response.ok) { session.state = "error"; session.error = `ElevenLabs transcription failed (${response.status}).`; await this.#save(workspace, registry); throw new DomainError("VOICE_STATE_CONFLICT", session.error, response.status >= 500); }
    const result = z.object({ text: z.string(), language_code: z.string().optional() }).passthrough().parse(await response.json());
    session.partial = result.text;
    session.updatedAt = new Date().toISOString();
    await this.#save(workspace, registry);
    return { session, transcriptId: input.transcriptId, text: result.text, languageCode: result.language_code ?? null };
  }
  async finalize(workspace: WorkspaceRecord, input: { sessionId: string; utteranceId: string; transcriptId: string; text: string; model: string }) { const registry = await this.#registry(workspace); const session = this.#session(registry, workspace.id, input.sessionId); if (registry.muted) throw new DomainError("VOICE_STATE_CONFLICT", "Voice input is muted."); if (registry.seenTranscriptIds.includes(input.transcriptId)) return { session, task: null, audioBase64: null, duplicate: true }; registry.seenTranscriptIds.push(input.transcriptId); if (registry.seenTranscriptIds.length > 5_000) registry.seenTranscriptIds.splice(0, registry.seenTranscriptIds.length - 5_000); const generation = session.generation; const turn: Turn = { utteranceId: input.utteranceId, transcriptId: input.transcriptId, text: input.text, final: true, response: null, taskId: null, createdAt: new Date().toISOString() }; if (registry.retainTranscripts) session.turns.push(turn); session.state = "thinking"; session.partial = input.text; session.activeUtteranceId = input.utteranceId; session.audioBase64 = null; session.error = null; await this.#save(workspace, registry);
    const task = await this.agents.start(workspace, { objective: input.text, model: input.model, maxSteps: 8, maxTokens: 50_000, maxRuntimeMs: 300_000, onTaskCreated: async (taskId) => { session.activeTaskId = taskId; turn.taskId = taskId; await this.#save(workspace, registry); } }); if (task.status !== "completed") { session.activeTaskId = null; session.state = session.generation === generation ? "idle" : session.state; session.error = task.error; await this.#save(workspace, registry); return { session, task, audioBase64: null }; } turn.response = task.output; const settings = await this.workspaces.getSettings(workspace.id); let audioBase64: string | null = null; if (settings.effective.voice.enabled && settings.effective.voice.voiceId && task.output && generation === session.generation) {
      const controller = new AbortController(); this.#speechControllers.set(session.id, controller);
      try { audioBase64 = await this.#synthesize(settings.effective.voice.voiceId, task.output, controller.signal); }
      catch (error) { if (generation !== session.generation || controller.signal.aborted) return { session, task, audioBase64: null }; session.state = "error"; session.error = error instanceof Error ? error.message : "Speech output failed."; session.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return { session, task, audioBase64: null }; }
      finally { if (this.#speechControllers.get(session.id) === controller) this.#speechControllers.delete(session.id); }
    } if (generation !== session.generation) audioBase64 = null; session.audioBase64 = audioBase64; session.state = audioBase64 ? "speaking" : "idle"; session.activeTaskId = null; session.updatedAt = new Date().toISOString(); await this.#save(workspace, registry); return { session, task, audioBase64 };
  }
  async interrupt(workspace: WorkspaceRecord, sessionId: string, cancelTask: boolean) { const registry = await this.#registry(workspace); const session = this.#session(registry, workspace.id, sessionId); this.#speechControllers.get(session.id)?.abort(); session.generation += 1; session.audioBase64 = null; session.state = "interrupted"; session.updatedAt = new Date().toISOString(); if (cancelTask && session.activeTaskId) await this.agents.cancel(workspace, session.activeTaskId).catch(() => undefined); await this.#save(workspace, registry); return session; }
  async played(workspace: WorkspaceRecord, sessionId: string, utteranceId: string) { const registry = await this.#registry(workspace); const session = this.#session(registry, workspace.id, sessionId); if (session.activeUtteranceId !== utteranceId) throw new DomainError("VOICE_STATE_CONFLICT", "Stale audio completion was ignored."); session.audioBase64 = null; session.state = "idle"; await this.#save(workspace, registry); return session; }
  async wake(workspace: WorkspaceRecord, phrase: string) { if (!isTestRuntime()) throw new DomainError("VOICE_STATE_CONFLICT", "No local wake-word engine is installed."); const registry = await this.#registry(workspace); if (!registry.wakeWordEnabled || registry.muted) return { activated: false, muted: registry.muted }; const session = await this.start(workspace, "conversation"); return { activated: true, phrase, session }; }
  async #synthesize(voiceId: string, text: string, signal: AbortSignal) { const key = this.credential(); if (!key) throw new DomainError("VOICE_STATE_CONFLICT", "An ElevenLabs credential is required for speech output."); const response = await this.fetchImpl(`${this.baseUrl}/v1/text-to-speech/${encodeURIComponent(voiceId)}/stream?output_format=mp3_44100_128`, { method: "POST", headers: { "Content-Type": "application/json", "xi-api-key": key }, body: JSON.stringify({ text, model_id: "eleven_flash_v2_5" }), signal }); if (!response.ok) throw new DomainError("VOICE_STATE_CONFLICT", `ElevenLabs speech failed (${response.status}).`, response.status >= 500); return Buffer.from(await response.arrayBuffer()).toString("base64"); }
  #session(registry: Registry, workspaceId: string, sessionId: string) { const session = registry.sessions.find((candidate) => candidate.id === sessionId && candidate.workspaceId === workspaceId); if (!session) throw new DomainError("WORKSPACE_CONFLICT", "Voice session does not belong to this workspace."); return session; }
  #path(workspace: WorkspaceRecord) { return join(workspace.canonicalPath, ".voidra", "voice.json"); }
  async #registry(workspace: WorkspaceRecord) { const cached = this.#registries.get(workspace.id); if (cached) return cached; let registry: Registry; try { registry = registrySchema.parse(JSON.parse(await readFile(this.#path(workspace), "utf8"))); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw new DomainError("INCOMPATIBLE_SCHEMA", "Voice metadata requires recovery."); registry = { schemaVersion: 1, wakeWordEnabled: false, muted: false, retainTranscripts: true, seenTranscriptIds: [], sessions: [] }; } for (const session of registry.sessions) if (["listening", "transcribing", "thinking", "speaking"].includes(session.state)) { session.state = "interrupted"; session.audioBase64 = null; session.error = "Voice session stopped with the runtime."; } this.#registries.set(workspace.id, registry); await this.#save(workspace, registry); return registry; }
  async #save(workspace: WorkspaceRecord, registry: Registry) { const previous = this.#saveQueues.get(workspace.id) ?? Promise.resolve(); const persisted: Registry = { ...registry, sessions: registry.sessions.map((session) => ({ ...session, audioBase64: null })) }; const current = previous.catch(() => undefined).then(() => atomicWrite(this.#path(workspace), persisted)); this.#saveQueues.set(workspace.id, current); await current; if (this.#saveQueues.get(workspace.id) === current) this.#saveQueues.delete(workspace.id); }
}
