import { _electron as electron, expect, test, type ElectronApplication, type Page } from "@playwright/test";
import { createServer, type Server } from "node:http";
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

let temporaryRoot: string; let application: ElectronApplication | undefined; let provider: Server | undefined;
test.beforeEach(async () => { temporaryRoot = await mkdtemp(join(tmpdir(), "voidra-automation-e2e-")); });
test.afterEach(async () => { if (application) await application.close().catch(() => undefined); application = undefined; if (provider) await new Promise<void>((resolve) => provider!.close(() => resolve())); provider = undefined; await rm(temporaryRoot, { recursive: true, force: true }); });
async function launch(profile: string, folders: string[] = [], env: Record<string, string> = {}) { return electron.launch({ args: [process.cwd()], env: { ...process.env, VOIDRA_E2E: "1", VOIDRA_USER_DATA_DIR: profile, VOIDRA_TEST_FOLDER_RESULTS: JSON.stringify(folders), ...env } }); }
async function onboard(window: Page, name: string) { await window.getByLabel("Workspace name").fill(name); await window.getByRole("button", { name: "Choose workspace folder" }).click(); await window.getByRole("button", { name: "Create workspace" }).click(); await expect(window.getByTestId("workspace-dialog")).toBeHidden(); }
async function workspaceId(window: Page) { return window.getByLabel("Current workspace").inputValue(); }
async function request(window: Page, owner: string, operation: string, payload: Record<string, unknown> = {}) { return window.evaluate(({ owner, operation, payload }) => globalThis.window.voidra!.service.request({ requestId: crypto.randomUUID(), workspaceId: owner, sessionId: crypto.randomUUID(), operation, payload } as any), { owner, operation, payload }); }

test("organizes an explicitly selected folder with review, traversal rejection, and undo", async () => {
  const workRoot = join(temporaryRoot, "Work"); const files = join(temporaryRoot, "Chosen Files"); await Promise.all([mkdir(workRoot), mkdir(files)]); await writeFile(join(files, "report.txt"), "report"); application = await launch(join(temporaryRoot, "profile"), [workRoot, files]); const window = await application.firstWindow(); await onboard(window, "Work"); await window.getByRole("link", { name: "Mac" }).click(); await expect(window.getByText("electron-macos")).toBeVisible();
  await window.getByLabel("Automation root name").fill("Fixture files"); await window.getByRole("button", { name: "Choose automation folder" }).click(); await window.getByRole("button", { name: "Add scoped root" }).click(); await expect(window.getByLabel("Automation root files")).toContainText("report.txt"); await window.getByLabel("Automation root files").getByRole("button", { name: /report.txt/ }).click(); await window.getByLabel("File action", { exact: true }).selectOption("move"); await window.getByLabel("File action destination").fill("Sorted/report.txt"); await window.getByRole("button", { name: "Prepare exact file action" }).click(); await expect(window.getByLabel("Automation actions")).toContainText("awaiting-approval"); await window.getByLabel("Automation actions").getByRole("button", { name: "Approve exact action" }).click(); await expect(window.getByLabel("Automation actions")).toContainText("completed"); expect(await readFile(join(files, "Sorted", "report.txt"), "utf8")).toBe("report"); await window.getByLabel("Automation actions").getByRole("button", { name: "Undo" }).click(); await expect(window.getByLabel("Automation actions")).toContainText("undone"); expect(await readFile(join(files, "report.txt"), "utf8")).toBe("report");
  await window.getByLabel("File action", { exact: true }).selectOption("trash"); await window.getByLabel("File action source").fill("../outside.txt"); await window.getByRole("button", { name: "Prepare exact file action" }).click(); await expect(window.getByRole("status")).toContainText("escapes"); await expect(stat(join(temporaryRoot, "outside.txt"))).rejects.toThrow();
});

test("reports permission denial as a failed native action without fabricated completion", async () => {
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot], { VOIDRA_NATIVE_FIXTURE: "1", VOIDRA_NATIVE_ACCESSIBILITY: "denied" }); const window = await application.firstWindow(); await onboard(window, "Work"); await window.getByRole("link", { name: "Mac" }).click(); await expect(window.getByText("deterministic-fixture")).toBeVisible(); await expect(window.getByText("denied")).toBeVisible(); await window.getByLabel("Native operation").selectOption("activate-control"); await window.getByLabel("Native target").fill(JSON.stringify({ appId: "dev.voidra.fixture", windowId: "fixture-window", controlId: "fixture-control", revision: "1" })); await window.getByRole("button", { name: "Prepare native action" }).click(); await window.getByLabel("Automation actions").getByRole("button", { name: "Approve exact action" }).click(); await expect(window.getByLabel("Automation actions")).toContainText("failed"); await expect(window.getByLabel("Automation actions")).toContainText("Accessibility permission is denied"); await expect(window.getByRole("status")).toContainText("Action failed");
});

test("runs a reviewed OpenRouter file action inside the selected root", async () => {
  let calls = 0; provider = createServer((requestMessage, response) => { let raw = ""; requestMessage.on("data", (chunk) => { raw += chunk; }); requestMessage.on("end", () => { calls += 1; const body = JSON.parse(raw) as { tools: Array<any> }; const fileTool = body.tools.find((tool) => tool.function?.name === "file_action"); const rootId = fileTool?.function.parameters.properties.rootId.enum[0]; const event = calls === 1 ? { model: "fixture/mac", choices: [{ delta: { tool_calls: [{ index: 0, id: "file-move", function: { name: "file_action", arguments: JSON.stringify({ rootId, action: "move", source: "brief.txt", destination: "Prepared/brief.txt" }) } }] }, finish_reason: "tool_calls" }] } : { model: "fixture/mac", choices: [{ delta: { content: "The selected file was organized." }, finish_reason: "stop" }] }; response.writeHead(200, { "Content-Type": "text/event-stream" }); response.end(`data: ${JSON.stringify(event)}\n\ndata: [DONE]\n\n`); }); }); await new Promise<void>((resolve) => provider!.listen(0, "127.0.0.1", resolve)); const address = provider.address(); if (!address || typeof address === "string") throw new Error("Provider fixture did not bind.");
  const workRoot = join(temporaryRoot, "Work"); const files = join(temporaryRoot, "Files"); await Promise.all([mkdir(workRoot), mkdir(files)]); await writeFile(join(files, "brief.txt"), "brief"); application = await launch(join(temporaryRoot, "profile"), [workRoot], { VOIDRA_OPENROUTER_BASE_URL: `http://127.0.0.1:${address.port}`, VOIDRA_OPENROUTER_TEST_KEY: "fixture-key", VOIDRA_NATIVE_FIXTURE: "1" }); const window = await application.firstWindow(); await onboard(window, "Work"); const owner = await workspaceId(window); expect((await request(window, owner, "automation.addRoot", { name: "Files", path: files })).ok).toBe(true); await window.getByRole("link", { name: "Assistant" }).click(); await window.getByLabel("Automatic task objective").fill("Organize the selected brief."); await window.getByLabel("Automatic task model").fill("fixture/mac"); await window.getByRole("button", { name: "Run automatic task" }).click(); await expect(window.getByLabel("Pending tool action")).toContainText("file_action"); await window.getByRole("button", { name: "Approve exact action" }).click(); await expect(window.getByLabel("Automatic tasks")).toContainText("completed"); expect(await readFile(join(files, "Prepared", "brief.txt"), "utf8")).toBe("brief"); const journal = await request(window, owner, "automation.list") as any; expect(journal.data.actions[0]).toMatchObject({ operation: "move", state: "completed" }); expect(calls).toBe(2);
});

test("rejects a stale inspected target before activation", async () => {
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot], { VOIDRA_NATIVE_FIXTURE: "1" }); const window = await application.firstWindow(); await onboard(window, "Work"); const owner = await workspaceId(window); const prepared = await request(window, owner, "automation.prepareNative", { operation: "activate-control", target: { appId: "dev.voidra.fixture", windowId: "fixture-window", controlId: "fixture-control", revision: "stale" } }); expect(prepared.ok).toBe(true); const approved = await request(window, owner, "automation.approveNative", { actionId: (prepared as any).data.id }); expect(approved).toMatchObject({ ok: true, data: { state: "failed", error: expect.stringContaining("target changed") } });
});

test("serializes two workspaces behind one desktop lease and takeover interrupts both", async () => {
  const workRoot = join(temporaryRoot, "Work"); const personalRoot = join(temporaryRoot, "Personal"); await Promise.all([mkdir(workRoot), mkdir(personalRoot)]); application = await launch(join(temporaryRoot, "profile"), [workRoot, personalRoot], { VOIDRA_NATIVE_FIXTURE: "1", VOIDRA_NATIVE_ACTION_DELAY_MS: "900" }); const window = await application.firstWindow(); await onboard(window, "Work"); const workId = await workspaceId(window); await window.getByRole("button", { name: "Add workspace" }).click(); await onboard(window, "Personal"); const personalId = await workspaceId(window);
  const workAction = await request(window, workId, "automation.prepareNative", { operation: "inspect-target", target: {} }); const personalAction = await request(window, personalId, "automation.prepareNative", { operation: "inspect-target", target: {} }); await window.evaluate(({ workId, actionId }) => { void globalThis.window.voidra!.service.request({ requestId: crypto.randomUUID(), workspaceId: workId, sessionId: crypto.randomUUID(), operation: "automation.approveNative", payload: { actionId } }); }, { workId, actionId: (workAction as any).data.id }); await expect.poll(async () => (await request(window, workId, "automation.capabilities") as any).data.leaseOwner?.workspaceId).toBe(workId);
  await window.evaluate(({ personalId, actionId }) => { void globalThis.window.voidra!.service.request({ requestId: crypto.randomUUID(), workspaceId: personalId, sessionId: crypto.randomUUID(), operation: "automation.approveNative", payload: { actionId } }); }, { personalId, actionId: (personalAction as any).data.id }); await expect.poll(async () => (await request(window, workId, "automation.capabilities") as any).data.queueDepth).toBe(1); await request(window, workId, "automation.takeover");
  await expect.poll(async () => ((await request(window, workId, "automation.list") as any).data.actions[0]?.state)).toBe("interrupted"); await expect.poll(async () => ((await request(window, personalId, "automation.list") as any).data.actions[0]?.state)).toBe("interrupted"); const status = await request(window, workId, "automation.capabilities") as any; expect(status.data.leaseOwner).toBeNull(); expect(status.data.queueDepth).toBe(0);
});
