import { _electron as electron, expect, test, type ElectronApplication, type Page } from "@playwright/test";
import { createServer, type Server } from "node:http";
import { mkdir, mkdtemp, readFile, realpath, rm, stat, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type { BrowserTabState } from "../../src/shared/browser-contracts";

let temporaryRoot: string; let application: ElectronApplication | undefined; let site: Server | undefined; let crossOriginSite: Server | undefined; let provider: Server | undefined; let siteUrl = ""; let crossOriginUrl = "";
test.beforeEach(async () => {
  temporaryRoot = await mkdtemp(join(tmpdir(), "voidra-browser-e2e-"));
  crossOriginSite = createServer((_request, response) => { response.writeHead(200, { "Content-Type": "text/html" }); response.end("<title>Outside</title><p>cross-origin destination</p>"); });
  await new Promise<void>((resolve) => crossOriginSite!.listen(0, "127.0.0.1", resolve)); const crossAddress = crossOriginSite.address(); if (!crossAddress || typeof crossAddress === "string") throw new Error("Cross-origin fixture did not bind."); crossOriginUrl = `http://127.0.0.1:${crossAddress.port}`;
  site = createServer((request, response) => {
    const url = new URL(request.url ?? "/", "http://fixture"); const cookie = request.headers.cookie ?? "";
    if (url.pathname === "/login") { response.writeHead(200, { "Content-Type": "text/html", "Set-Cookie": `account=${url.searchParams.get("name") ?? "unknown"}; Path=/; HttpOnly` }); response.end("<title>Fixture login</title><input id='name'><button id='save'>Save</button><form id='commit'><button id='submit' type='submit'>Submit</button></form><button id='permission'>Permission</button><a id='popup' target='_blank' href='/status'>Popup</a><a id='download' download href='/download'>Download</a><a id='redirect' href='/redirect'>Redirect</a><a id='outside' href='/outside'>Outside</a><output id='result'></output><script>document.querySelector('#save').onclick=()=>document.querySelector('#result').textContent=document.querySelector('#name').value;document.querySelector('#commit').onsubmit=(event)=>{event.preventDefault();document.querySelector('#result').textContent='submitted once'};document.querySelector('#permission').onclick=()=>navigator.geolocation.getCurrentPosition(()=>result.textContent='permission allowed',()=>result.textContent='permission denied')</script>"); return; }
    if (url.pathname === "/status") { response.writeHead(200, { "Content-Type": "text/html" }); response.end(`<title>Fixture status</title><p id='account'>${cookie || "no-account"}</p>`); return; }
    if (url.pathname === "/redirect") { response.writeHead(302, { Location: "/status" }); response.end(); return; }
    if (url.pathname === "/outside") { response.writeHead(302, { Location: crossOriginUrl }); response.end(); return; }
    if (url.pathname === "/download") { response.writeHead(200, { "Content-Type": "text/plain", "Content-Disposition": "attachment; filename=fixture.txt" }); response.end("workspace download"); return; }
    response.writeHead(200, { "Content-Type": "text/html" }); response.end("<title>Fixture home</title><p>home</p>");
  });
  await new Promise<void>((resolve) => site!.listen(0, "127.0.0.1", resolve)); const address = site.address(); if (!address || typeof address === "string") throw new Error("Fixture did not bind."); siteUrl = `http://127.0.0.1:${address.port}`;
});
test.afterEach(async () => { if (application) await application.close().catch(() => undefined); application = undefined; for (const server of [site, crossOriginSite, provider]) if (server) await new Promise<void>((resolve) => server.close(() => resolve())); site = undefined; crossOriginSite = undefined; provider = undefined; await rm(temporaryRoot, { recursive: true, force: true }); });

async function launch(profile: string, folders: string[] = [], env: Record<string, string> = {}) { return electron.launch({ args: [process.cwd()], env: { ...process.env, VOIDRA_E2E: "1", VOIDRA_USER_DATA_DIR: profile, VOIDRA_TEST_FOLDER_RESULTS: JSON.stringify(folders), ...env } }); }
async function onboard(window: Page, name: string) { await window.getByLabel("Workspace name").fill(name); await window.getByRole("button", { name: "Choose workspace folder" }).click(); await window.getByRole("button", { name: "Create workspace" }).click(); await expect(window.getByTestId("workspace-dialog")).toBeHidden(); await expect(window.getByLabel("Current workspace")).toHaveValue(/[0-9a-f-]{36}/); }
async function selectedWorkspaceId(window: Page) { return window.getByLabel("Current workspace").inputValue(); }
async function browserState(window: Page, workspaceId: string, workspaceRoot: string) { return window.evaluate(({ workspaceId, workspaceRoot }) => globalThis.window.voidra!.browser.list(workspaceId, workspaceRoot), { workspaceId, workspaceRoot }); }
async function firstTab(window: Page, workspaceId: string, workspaceRoot: string) { await expect.poll(async () => (await browserState(window, workspaceId, workspaceRoot)).tabs.length).toBeGreaterThan(0); return (await browserState(window, workspaceId, workspaceRoot)).tabs[0]!; }
async function waitForTab(window: Page, workspaceId: string, workspaceRoot: string, predicate: (tab: BrowserTabState) => boolean) {
  await expect.poll(async () => (await browserState(window, workspaceId, workspaceRoot)).tabs.some(predicate)).toBe(true);
  return (await browserState(window, workspaceId, workspaceRoot)).tabs.find(predicate)!;
}
async function readAssignedTab(window: Page, workspaceId: string, tab: BrowserTabState) {
  const assigned = tab.assignedTaskId ? tab : await window.evaluate(({ workspaceId, tabId }) => globalThis.window.voidra!.browser.assign(workspaceId, tabId, crypto.randomUUID()), { workspaceId, tabId: tab.id });
  return window.evaluate(({ workspaceId, tab }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, tab.assignedTaskId!, tab.documentId, { kind: "read" }), { workspaceId, tab: assigned });
}

test("keeps cookies, tabs, downloads, and handles inside their owning workspace across restart", async () => {
  const workRoot = join(temporaryRoot, "Work"); const personalRoot = join(temporaryRoot, "Personal"); const profile = join(temporaryRoot, "profile"); await Promise.all([mkdir(workRoot), mkdir(personalRoot)]);
  application = await launch(profile, [workRoot, personalRoot]); let window = await application.firstWindow(); await onboard(window, "Work"); const workId = await selectedWorkspaceId(window); await window.getByRole("link", { name: "Browser", exact: true }).click();
  let work = await firstTab(window, workId, workRoot); await window.evaluate(({ workId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workId, tabId, url), { workId, tabId: work.id, url: `${siteUrl}/login?name=work` }); work = await waitForTab(window, workId, workRoot, (tab) => tab.id === work.id && !tab.loading && tab.url.includes("/login"));
  const taskId = crypto.randomUUID(); work = await window.evaluate(({ workId, tabId, taskId }) => globalThis.window.voidra!.browser.assign(workId, tabId, taskId), { workId, tabId: work.id, taskId });
  await window.evaluate(({ workId, tab, taskId }) => globalThis.window.voidra!.browser.action(workId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#download" }), { workId, tab: work, taskId }); await expect.poll(async () => readFile(join(workRoot, "Downloads", "fixture.txt"), "utf8").catch(() => "")).toBe("workspace download");
  await window.getByRole("button", { name: "Add workspace" }).click(); await onboard(window, "Personal"); await expect(stat(join(personalRoot, "Downloads", "fixture.txt"))).rejects.toThrow(); const personalId = await selectedWorkspaceId(window); await window.getByRole("link", { name: "Browser", exact: true }).click(); let personal = await firstTab(window, personalId, personalRoot);
  await window.evaluate(({ personalId, tabId, url }) => globalThis.window.voidra!.browser.navigate(personalId, tabId, url), { personalId, tabId: personal.id, url: `${siteUrl}/status` }); personal = await waitForTab(window, personalId, personalRoot, (tab) => tab.id === personal.id && !tab.loading && tab.url.includes("/status")); expect((await readAssignedTab(window, personalId, personal)).text).toContain("no-account");
  await expect(window.evaluate(({ personalId, workTabId }) => globalThis.window.voidra!.browser.reload(personalId, workTabId).then(() => "allowed").catch((error) => error.message), { personalId, workTabId: work.id })).resolves.toContain("does not belong");
  await application.close(); application = await launch(profile); window = await application.firstWindow(); await window.getByRole("link", { name: "Browser", exact: true }).click(); await window.getByLabel("Current workspace").selectOption(workId); work = await waitForTab(window, workId, workRoot, (tab) => tab.id === work.id && !tab.loading); await window.evaluate(({ workId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workId, tabId, url), { workId, tabId: work.id, url: `${siteUrl}/status` }); work = await waitForTab(window, workId, workRoot, (tab) => tab.id === work.id && !tab.loading && tab.url.includes("/status")); expect((await readAssignedTab(window, workId, work)).text).toContain("account=work");
});

test("binds agent actions to a current document and pauses them for user takeover", async () => {
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot]); const window = await application.firstWindow(); await onboard(window, "Work"); const workspaceId = await selectedWorkspaceId(window); await window.getByRole("link", { name: "Browser", exact: true }).click();
  let tab = await firstTab(window, workspaceId, workRoot); await window.evaluate(({ workspaceId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workspaceId, tabId, url), { workspaceId, tabId: tab.id, url: `${siteUrl}/login?name=work` }); tab = await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading && item.url.includes("/login")); const staleDocumentId = tab.documentId; const taskId = crypto.randomUUID(); tab = await window.evaluate(({ workspaceId, tabId, taskId }) => globalThis.window.voidra!.browser.assign(workspaceId, tabId, taskId), { workspaceId, tabId: tab.id, taskId });
  await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "type", selector: "#name", text: "agent value" }), { workspaceId, tab, taskId }); await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#save" }), { workspaceId, tab, taskId });
  await window.evaluate(({ workspaceId, tabId }) => globalThis.window.voidra!.browser.takeover(workspaceId, tabId), { workspaceId, tabId: tab.id }); expect(await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "read" }).then(() => "allowed").catch((error) => error.message), { workspaceId, tab, taskId })).toContain("paused");
  await window.evaluate(({ workspaceId, tabId }) => globalThis.window.voidra!.browser.resume(workspaceId, tabId), { workspaceId, tabId: tab.id }); tab = await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && item.control === "agent"); expect((await readAssignedTab(window, workspaceId, tab)).text).toContain("agent value");
  await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#permission" }), { workspaceId, tab, taskId }); await expect.poll(async () => (await readAssignedTab(window, workspaceId, (await browserState(window, workspaceId, workRoot)).tabs.find((item) => item.id === tab.id)!)).text ?? "").toContain("permission denied");
  await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#redirect" }), { workspaceId, tab, taskId }); tab = await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading && item.url.includes("/status")); expect(await window.evaluate(({ workspaceId, tab, taskId, staleDocumentId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, staleDocumentId, { kind: "read" }).then(() => "allowed").catch((error) => error.message), { workspaceId, tab, taskId, staleDocumentId })).toContain("page changed");
  await window.evaluate(({ workspaceId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workspaceId, tabId, url), { workspaceId, tabId: tab.id, url: `${siteUrl}/login?name=work` }); tab = await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading && item.url.includes("/login")); tab = await window.evaluate(({ workspaceId, tabId, taskId }) => globalThis.window.voidra!.browser.assign(workspaceId, tabId, taskId), { workspaceId, tabId: tab.id, taskId }); await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#outside" }), { workspaceId, tab, taskId }); await expect.poll(async () => (await browserState(window, workspaceId, workRoot)).tabs.find((item) => item.id === tab.id)?.blockedReason ?? "").toContain("approved origin");
  tab = await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading); await window.evaluate(({ workspaceId, tab, taskId }) => globalThis.window.voidra!.browser.action(workspaceId, tab.id, taskId, tab.documentId, { kind: "click", selector: "#popup" }), { workspaceId, tab, taskId }); await expect.poll(async () => (await browserState(window, workspaceId, workRoot)).tabs.find((item) => item.id === tab.id)?.blockedReason ?? "").toContain("Popup blocked");
  await application!.evaluate(({ webContents }, origin) => { const contents = webContents.getAllWebContents().find((item) => item.getURL().startsWith(origin)); if (!contents) throw new Error("Browser contents not found"); contents.forcefullyCrashRenderer(); }, siteUrl); await expect.poll(async () => (await browserState(window, workspaceId, workRoot)).tabs.find((item) => item.id === tab.id)?.crashed).toBe(true); await window.evaluate(({ workspaceId, tabId }) => globalThis.window.voidra!.browser.reload(workspaceId, tabId), { workspaceId, tabId: tab.id }); await expect.poll(async () => (await browserState(window, workspaceId, workRoot)).tabs.find((item) => item.id === tab.id)?.crashed).toBe(false); await expect(window.getByRole("heading", { name: "Browser" })).toBeVisible();
});

test("routes an approved OpenRouter browser tool through the assigned observable tab", async () => {
  let calls = 0; let advertisedBrowserTool = false;
  provider = createServer((request, response) => { let raw = ""; request.on("data", (chunk) => { raw += chunk; }); request.on("end", () => {
    calls += 1; const body = JSON.parse(raw) as { tools: Array<any> }; const browserTool = body.tools.find((tool) => tool.function?.name === "browser_action"); advertisedBrowserTool ||= Boolean(browserTool); const tabId = browserTool?.function.parameters.properties.tabId.enum[0]; const description = String(browserTool?.function.description ?? ""); const documentId = description.match(/document ([0-9a-f-]{36})/)?.[1];
    const event = calls === 1 ? { model: "fixture/browser", choices: [{ delta: { tool_calls: [{ index: 0, id: "browser-type", function: { name: "browser_action", arguments: JSON.stringify({ tabId, documentId, action: "type", selector: "#name", text: "OpenRouter filled this" }) } }] }, finish_reason: "tool_calls" }] } : { model: "fixture/browser", choices: [{ delta: { content: "The assigned browser field is filled." }, finish_reason: "stop" }] };
    response.writeHead(200, { "Content-Type": "text/event-stream" }); response.end(`data: ${JSON.stringify(event)}\n\ndata: [DONE]\n\n`);
  }); }); await new Promise<void>((resolve) => provider!.listen(0, "127.0.0.1", resolve)); const address = provider.address(); if (!address || typeof address === "string") throw new Error("Provider fixture did not bind.");
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot], { VOIDRA_OPENROUTER_BASE_URL: `http://127.0.0.1:${address.port}`, VOIDRA_OPENROUTER_TEST_KEY: "fixture-key" }); const window = await application.firstWindow(); await onboard(window, "Work"); const workspaceId = await selectedWorkspaceId(window); await window.getByRole("link", { name: "Browser", exact: true }).click(); const tab = await firstTab(window, workspaceId, workRoot); await window.evaluate(({ workspaceId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workspaceId, tabId, url), { workspaceId, tabId: tab.id, url: `${siteUrl}/login?name=work` }); await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading && item.url.includes("/login"));
  await window.getByLabel("Browser task objective").fill("Fill the name field with the requested value."); await window.getByLabel("Browser task model").fill("fixture/browser"); await window.getByRole("button", { name: "Run with OpenRouter" }).click(); await expect(window.locator("p.save-message")).toContainText("awaiting approval"); await window.getByRole("link", { name: "Assistant" }).click(); await expect(window.getByLabel("Pending tool action")).toContainText("browser_action"); await window.getByRole("button", { name: "Approve exact action" }).click(); await expect(window.getByLabel("Automatic tasks")).toContainText("completed"); await expect(window.getByLabel("Automatic task output")).toContainText("assigned browser field is filled");
  const value = await application.evaluate(async ({ webContents }, origin) => { const contents = webContents.getAllWebContents().find((item) => item.getURL().startsWith(origin)); if (!contents) throw new Error("Browser contents not found"); return contents.executeJavaScript("document.querySelector('#name').value"); }, siteUrl); expect(value).toBe("OpenRouter filled this"); expect(advertisedBrowserTool).toBe(true); expect(calls).toBe(2);
});

test("interrupts an uncertain browser submission instead of replaying it", async () => {
  let calls = 0;
  provider = createServer((request, response) => { let raw = ""; request.on("data", (chunk) => { raw += chunk; }); request.on("end", () => { calls += 1; const body = JSON.parse(raw) as { tools: Array<any> }; const browserTool = body.tools.find((tool) => tool.function?.name === "browser_action"); const tabId = browserTool?.function.parameters.properties.tabId.enum[0]; const documentId = String(browserTool?.function.description ?? "").match(/document ([0-9a-f-]{36})/)?.[1]; const event = { model: "fixture/browser", choices: [{ delta: { tool_calls: [{ index: 0, id: "browser-submit", function: { name: "browser_action", arguments: JSON.stringify({ tabId, documentId, action: "click", selector: "#submit" }) } }] }, finish_reason: "tool_calls" }] }; response.writeHead(200, { "Content-Type": "text/event-stream" }); response.end(`data: ${JSON.stringify(event)}\n\ndata: [DONE]\n\n`); }); }); await new Promise<void>((resolve) => provider!.listen(0, "127.0.0.1", resolve)); const address = provider.address(); if (!address || typeof address === "string") throw new Error("Provider fixture did not bind.");
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot], { VOIDRA_OPENROUTER_BASE_URL: `http://127.0.0.1:${address.port}`, VOIDRA_OPENROUTER_TEST_KEY: "fixture-key" }); const window = await application.firstWindow(); await onboard(window, "Work"); const workspaceId = await selectedWorkspaceId(window); await window.getByRole("link", { name: "Browser", exact: true }).click(); const tab = await firstTab(window, workspaceId, workRoot); await window.evaluate(({ workspaceId, tabId, url }) => globalThis.window.voidra!.browser.navigate(workspaceId, tabId, url), { workspaceId, tabId: tab.id, url: `${siteUrl}/login?name=work` }); await waitForTab(window, workspaceId, workRoot, (item) => item.id === tab.id && !item.loading && item.url.includes("/login")); await window.getByLabel("Browser task model").fill("fixture/browser"); await window.getByRole("button", { name: "Run with OpenRouter" }).click(); await expect(window.locator("p.save-message")).toContainText("awaiting approval"); await window.getByRole("link", { name: "Assistant" }).click(); await window.getByRole("button", { name: "Approve exact action" }).click(); await expect(window.getByLabel("Automatic tasks")).toContainText("interrupted"); await expect(window.getByLabel("Automatic task output")).toContainText("outcome is uncertain"); await new Promise((resolve) => setTimeout(resolve, 150)); expect(calls).toBe(1);
});

test("reviews and runs component artifacts without a privileged bridge or network, then invalidates changed source", async () => {
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot]); const window = await application.firstWindow(); await onboard(window, "Work"); await window.getByRole("link", { name: "Browser", exact: true }).click(); await window.getByRole("button", { name: "Artifacts" }).click(); await window.getByLabel("Artifact name").fill("Fixture report"); await window.getByRole("button", { name: "Create component artifact" }).click(); await expect(window.getByRole("status")).toContainText("quarantine"); await expect(window.getByLabel("Artifact files")).toContainText("src/Artifact.tsx"); await window.getByRole("button", { name: "Run security review" }).click(); await expect.poll(async () => { const id = await selectedWorkspaceId(window); const [item] = await window.evaluate(({ id, root }) => globalThis.window.voidra!.artifacts.list(id, root), { id, root: workRoot }); return JSON.stringify({ static: item?.securityReview?.verdict, semantic: item?.semanticReview?.verdict, evidence: item?.semanticReview?.evidenceMode, decision: item?.reviewDecision?.verdict }); }).toContain('"decision":"approved"'); await expect(window.getByRole("status")).toContainText("digest approved"); expect(await readFile(join(workRoot, ".voidra", "artifact-review-journal.jsonl"), "utf8")).toContain('"evidenceMode":"test-fixture"');
  await expect.poll(() => application!.evaluate(({ webContents }) => webContents.getAllWebContents().some((contents) => contents.getURL().startsWith("voidra-artifact://")))).toBe(true);
  const networkTarget = `${siteUrl}/status`;
  const isolation = await application.evaluate(async ({ webContents }, networkTarget) => {
    const preview = webContents.getAllWebContents().find((contents) => contents.getURL().startsWith("voidra-artifact://")); if (!preview) throw new Error("Artifact preview not found");
    return preview.executeJavaScript(`(async()=>{document.querySelector('.va-action').click();await new Promise(r=>setTimeout(r,20));let network='allowed';try{await fetch(${JSON.stringify(networkTarget)})}catch{network='blocked'}let escape='allowed';try{const response=await fetch('/%2e%2e/workspace.json');escape=response.ok?'allowed':'blocked'}catch{escape='blocked'}return{interaction:document.querySelector('.va-metric strong').textContent,bridge:typeof window.voidra,capabilityBridge:typeof window.voidraArtifact,network,escape}})()`);
  }, networkTarget);
  expect(isolation).toMatchObject({ interaction: "1", bridge: "undefined", capabilityBridge: "object", network: "blocked", escape: "blocked" });
  const workspaceIdBeforeEdit = await selectedWorkspaceId(window); const [approvedArtifact] = await window.evaluate(({ workspaceId, root }) => globalThis.window.voidra!.artifacts.list(workspaceId, root), { workspaceId: workspaceIdBeforeEdit, root: workRoot }); const registryPath = join(workRoot, ".voidra", "artifacts.json"); const originalRegistry = await readFile(registryPath, "utf8"); const tamperedRegistry = JSON.parse(originalRegistry); tamperedRegistry[0].reviewDecision.signature = "0".repeat(64); await writeFile(registryPath, JSON.stringify(tamperedRegistry)); await expect(window.evaluate(({ workspaceId, root, artifactId }) => globalThis.window.voidra!.artifacts.preview(workspaceId, root, artifactId, { x: 0, y: 0, width: 600, height: 400 }).then(() => "allowed").catch((error) => error.message), { workspaceId: workspaceIdBeforeEdit, root: workRoot, artifactId: approvedArtifact!.id })).resolves.toContain("signature is invalid"); await writeFile(registryPath, originalRegistry);
  const componentPath = join(workRoot, ".voidra", "artifacts", approvedArtifact!.id, "src", "Artifact.tsx"); const originalComponent = await readFile(componentPath, "utf8"); await writeFile(componentPath, `${originalComponent}\n// out-of-band change\n`); await expect(window.evaluate(({ workspaceId, root, artifactId }) => globalThis.window.voidra!.artifacts.preview(workspaceId, root, artifactId, { x: 0, y: 0, width: 600, height: 400 }).then(() => "allowed").catch((error) => error.message), { workspaceId: workspaceIdBeforeEdit, root: workRoot, artifactId: approvedArtifact!.id })).resolves.toContain("source changed"); await writeFile(componentPath, originalComponent);
  await window.getByRole("button", { name: "src/Artifact.tsx" }).click(); const edited = (await window.getByLabel("Artifact source").inputValue()).replace("Reviewed Voidra component artifact", "Edited reviewed component"); await window.getByLabel("Artifact source").fill(edited); await window.getByRole("button", { name: "Save and reload" }).click(); await expect(window.getByRole("status")).toContainText("saved"); await expect(window.getByRole("button", { name: "Preview" })).toBeDisabled(); await window.getByRole("button", { name: "Run security review" }).click(); await expect(window.getByRole("status")).toContainText("digest approved");
  await window.getByRole("button", { name: "Export bundle" }).click(); await expect(window.getByRole("status")).toContainText("Exported to"); const workspaceId = await selectedWorkspaceId(window); const [artifact] = await window.evaluate(({ workspaceId, root }) => globalThis.window.voidra!.artifacts.list(workspaceId, root), { workspaceId, root: workRoot }); expect(artifact).toBeTruthy(); expect(artifact!.versions).toHaveLength(2); await expect(stat(join(workRoot, "Artifact Exports", `Fixture-report-${artifact!.revision.slice(0, 8)}`, "src", "Artifact.tsx"))).resolves.toBeTruthy(); const decisions = (await readFile(join(workRoot, ".voidra", "artifact-review-journal.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); expect(decisions).toHaveLength(2); expect(decisions[1].previousSignature).toBe(decisions[0].signature);
  const restored = await window.evaluate(({ workspaceId, root, artifactId, sourceDigest }) => globalThis.window.voidra!.artifacts.rollback(workspaceId, root, artifactId, sourceDigest), { workspaceId, root: workRoot, artifactId: artifact!.id, sourceDigest: approvedArtifact!.sourceDigest! }); expect(restored.reviewState).toBe("quarantined"); expect(restored.versions).toHaveLength(2); expect(await readFile(join(workRoot, ".voidra", "artifacts", artifact!.id, "src", "Artifact.tsx"), "utf8")).toContain("Reviewed Voidra component artifact");
  await expect(window.evaluate(({ workspaceId, root, artifactId }) => globalThis.window.voidra!.artifacts.read(workspaceId, root, artifactId, "../workspace.json").then(() => "allowed").catch((error) => error.message), { workspaceId, root: workRoot, artifactId: artifact!.id })).resolves.toContain("escapes");
  const outside = join(workRoot, "outside.txt"); await writeFile(outside, "private"); await symlink(outside, join(workRoot, ".voidra", "artifacts", artifact!.id, "escape.txt")); await expect(window.evaluate(({ workspaceId, root, artifactId }) => globalThis.window.voidra!.artifacts.read(workspaceId, root, artifactId, "escape.txt").then(() => "allowed").catch((error) => error.message), { workspaceId, root: workRoot, artifactId: artifact!.id })).resolves.toContain("symbolic links");
  await application.evaluate(({ webContents }) => { const preview = webContents.getAllWebContents().find((contents) => contents.getURL().startsWith("voidra-artifact://")); preview?.forcefullyCrashRenderer(); }); await expect(window.getByRole("heading", { name: "Browser" })).toBeVisible();
});

test("converts legacy HTML into a separate quarantined component scaffold without executing or overwriting it", async () => {
  const workRoot = join(temporaryRoot, "Work"); await mkdir(workRoot); application = await launch(join(temporaryRoot, "profile"), [workRoot]); const window = await application.firstWindow(); await onboard(window, "Work"); const workspaceId = await selectedWorkspaceId(window);
  const canonicalWorkRoot = await realpath(workRoot); const legacyId = crypto.randomUUID(); const legacyRoot = join(canonicalWorkRoot, ".voidra", "artifacts", legacyId); await mkdir(legacyRoot, { recursive: true }); const legacyHtml = "<h1>Legacy report</h1><script>globalThis.__legacyExecuted=true;fetch('https://example.com')</script>"; await writeFile(join(legacyRoot, "index.html"), legacyHtml); const now = new Date().toISOString(); await writeFile(join(canonicalWorkRoot, ".voidra", "artifacts.json"), `${JSON.stringify([{ id: legacyId, workspaceId, runId: null, name: "Legacy report", entryFile: "index.html", sourceNoteIds: [], files: ["index.html"], revision: "a".repeat(64), createdAt: now, updatedAt: now, root: legacyRoot, kind: "legacy-html", reviewState: "legacy", sourceDigest: "a".repeat(64), bundleDigest: null, requestedCapabilities: [], grants: [], securityReview: null, semanticReview: null, reviewDecision: null }])}\n`);
  const converted = await window.evaluate(({ workspaceId, workRoot, legacyId }) => globalThis.window.voidra!.artifacts.convertLegacy(workspaceId, workRoot, legacyId), { workspaceId, workRoot, legacyId }); expect(converted).toMatchObject({ kind: "component", reviewState: "quarantined", legacySourceId: legacyId }); expect(await readFile(join(legacyRoot, "index.html"), "utf8")).toBe(legacyHtml); const source = await readFile(join(workRoot, ".voidra", "artifacts", converted.id, "src", "Artifact.tsx"), "utf8"); expect(source).toContain("Guided conversion"); expect(source).not.toContain("fetch("); expect(source).not.toContain("__legacyExecuted");
});
