import { _electron as electron, expect, test, type ElectronApplication, type Page } from "@playwright/test";
import { createServer, type Server } from "node:http";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

let temporaryRoot: string; let application: ElectronApplication | undefined; let provider: Server | undefined;
test.beforeEach(async () => { temporaryRoot = await mkdtemp(join(tmpdir(), "voidra-remote-e2e-")); });
test.afterEach(async () => { if (application) await application.close().catch(() => undefined); application = undefined; if (provider) await new Promise<void>((resolve) => provider!.close(() => resolve())); provider = undefined; await rm(temporaryRoot, { recursive: true, force: true }); });
async function providerFixture() { let calls = 0; provider = createServer((request, response) => { let raw = ""; request.on("data", (chunk) => { raw += chunk; }); request.on("end", () => { calls += 1; const body = JSON.parse(raw); const objective = String(body.messages.at(-1)?.content ?? ""); const event = { model: "fixture/remote", choices: [{ delta: { content: `Remote completed: ${objective}` }, finish_reason: "stop" }] }; response.writeHead(200, { "Content-Type": "text/event-stream" }); response.end(`data: ${JSON.stringify(event)}\n\ndata: [DONE]\n\n`); }); }); await new Promise<void>((resolve) => provider!.listen(0, "127.0.0.1", resolve)); const address = provider.address(); if (!address || typeof address === "string") throw new Error("Provider did not bind."); return { url: `http://127.0.0.1:${address.port}`, calls: () => calls }; }
async function launch(profile: string, folders: string[], baseUrl: string) { return electron.launch({ args: [process.cwd()], env: { ...process.env, VOIDRA_E2E: "1", VOIDRA_REMOTE_GATEWAY_TEST: "1", VOIDRA_USER_DATA_DIR: profile, VOIDRA_TEST_FOLDER_RESULTS: JSON.stringify(folders), VOIDRA_OPENROUTER_BASE_URL: baseUrl, VOIDRA_OPENROUTER_TEST_KEY: "fixture-key" } }); }
async function onboard(window: Page, name: string) { await window.getByLabel("Workspace name").fill(name); await window.getByRole("button", { name: "Choose workspace folder" }).click(); await window.getByRole("button", { name: "Create workspace" }).click(); await expect(window.getByTestId("workspace-dialog")).toBeHidden(); }
async function request(window: Page, workspaceId: string, operation: string, payload: Record<string, unknown> = {}) { return window.evaluate(({ workspaceId, operation, payload }) => globalThis.window.voidra!.service.request({ requestId: crypto.randomUUID(), workspaceId, sessionId: crypto.randomUUID(), operation, payload } as any), { workspaceId, operation, payload }); }

test("pairs a separate companion for Personal only, submits once across retry, rejects offline work, and revokes immediately", async () => {
  const fixture = await providerFixture(); const workRoot = join(temporaryRoot, "Work"); const personalRoot = join(temporaryRoot, "Personal"); await Promise.all([mkdir(workRoot), mkdir(personalRoot)]);
  application = await launch(join(temporaryRoot, "profile"), [workRoot, personalRoot], fixture.url); const host = await application.firstWindow(); await onboard(host, "Work"); const workId = await host.getByLabel("Current workspace").inputValue(); await host.getByRole("button", { name: "Add workspace" }).click(); await onboard(host, "Personal"); const personalId = await host.getByLabel("Current workspace").inputValue();
  await host.getByRole("link", { name: "Remote" }).click(); await expect(host.getByRole("heading", { name: "Companion ready" })).toBeVisible(); await host.getByLabel("Remote device name").fill("Test phone"); await host.getByRole("button", { name: "Create pairing code" }).click(); const code = await host.getByTestId("pairing-code").textContent(); const status = await request(host, personalId, "remote.status") as any; const url = status.data.url as string;
  const opened = application.waitForEvent("window"); await application.evaluate(async ({ BrowserWindow }, target) => { const window = new BrowserWindow({ width: 430, height: 800, webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true } }); await window.loadURL(target); }, url); const companion = await opened;
  await companion.getByLabel("Device name").fill("Phone renderer"); await companion.getByLabel("Six-digit code").fill(code!); await companion.getByRole("button", { name: "Pair" }).click(); await expect(companion.getByText("Mac online")).toBeVisible(); await expect(companion.getByLabel("Workspace")).toHaveText("Personal"); await expect(companion.getByLabel("Workspace")).not.toContainText("Work");
  const unauthorized = await companion.evaluate(async ({ workspaceId }) => { const token = localStorage.getItem("voidra-token"); const response = await fetch("/api/tasks", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, idempotencyKey: "forged-work", objective: "Read Work", model: "fixture/remote" }) }); return { status: response.status, body: await response.json() }; }, { workspaceId: workId }); expect(unauthorized).toMatchObject({ status: 401, body: { error: expect.stringContaining("not authorized") } });
  const retries = await companion.evaluate(async ({ workspaceId }) => { const token = localStorage.getItem("voidra-token"); const call = () => fetch("/api/tasks", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, idempotencyKey: "same-request", objective: "Personal update", model: "fixture/remote" }) }).then((response) => response.json()); return [await call(), await call()]; }, { workspaceId: personalId }); expect(retries[0]).toMatchObject({ duplicate: false, task: { status: "completed", output: "Remote completed: Personal update" } }); expect(retries[1]).toMatchObject({ duplicate: true, taskId: retries[0].taskId }); expect(fixture.calls()).toBe(1);
  await companion.getByLabel("Objective").fill("Prepare a manual Personal plan"); await expect(companion.getByLabel("Manual routine")).toContainText("Plan the Day"); await companion.getByRole("button", { name: "Prepare manual handoff" }).click(); await expect(companion.locator("#message")).toContainText("# Manual"); expect(fixture.calls()).toBe(1); await companion.getByRole("button", { name: "Copy prepared prompt" }).click(); await expect(companion.locator("#message")).toContainText("Paste it into the selected subscription client yourself");
  await companion.getByLabel("Objective").fill("Voice from Personal"); await companion.getByLabel("OpenRouter model").fill("fixture/remote"); await companion.getByRole("button", { name: "Run voice turn" }).click(); await expect(companion.locator("#message")).toContainText("Remote completed: Voice from Personal"); expect(fixture.calls()).toBe(2); const personalTasks = await request(host, personalId, "agent.list") as any; const workTasks = await request(host, workId, "agent.list") as any; expect(personalTasks.data.tasks.some((entry: any) => entry.objective === "Voice from Personal")).toBe(true); expect(workTasks.data.tasks).toEqual([]);
  await request(host, personalId, "remote.setAvailabilityFixture", { available: false }); const offline = await companion.evaluate(async ({ workspaceId }) => { const token = localStorage.getItem("voidra-token"); const response = await fetch("/api/tasks", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, idempotencyKey: "offline", objective: "Never queue", model: "fixture/remote" }) }); return { status: response.status, body: await response.json() }; }, { workspaceId: personalId }); expect(offline).toMatchObject({ status: 503, body: { error: expect.stringContaining("not queued") } }); await request(host, personalId, "remote.setAvailabilityFixture", { available: true }); expect(fixture.calls()).toBe(2);
  await expect(host.getByText("Phone renderer")).toBeVisible(); await host.getByRole("button", { name: "Revoke" }).click(); const revoked = await companion.evaluate(async () => { const token = localStorage.getItem("voidra-token"); const response = await fetch("/api/status", { headers: { Authorization: `Bearer ${token}` } }); return response.status; }); expect(revoked).toBe(401);
});
