"use client";

import { useCallback, useEffect, useState } from "react";
import type { RequestService } from "@/components/service-types";

type Root = { id: string; name: string; path: string };
type Action = { id: string; kind: "file" | "native"; operation: string; state: string; source: string | null; destination: string | null; target: Record<string, unknown> | null; result: Record<string, unknown> | null; error: string | null; undo: Record<string, unknown> | null };

export function AutomationPanel({ workspaceId, request }: { workspaceId: string; request: RequestService }) {
  const [roots, setRoots] = useState<Root[]>([]); const [actions, setActions] = useState<Action[]>([]); const [capabilities, setCapabilities] = useState<Record<string, unknown>>({}); const [files, setFiles] = useState<Array<{ name: string; path: string; type: string }>>([]);
  const [rootName, setRootName] = useState("Downloads fixture"); const [rootPath, setRootPath] = useState(""); const [rootId, setRootId] = useState("");
  const [fileAction, setFileAction] = useState<"copy" | "move" | "trash" | "write">("move"); const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [content, setContent] = useState("");
  const [nativeOperation, setNativeOperation] = useState<"open-path" | "open-app" | "inspect-target" | "activate-control">("inspect-target"); const [nativeTarget, setNativeTarget] = useState("{}"); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [list, status] = await Promise.all([request("automation.list", {}, workspaceId), request("automation.capabilities", {}, workspaceId)]); if (list.ok) { const nextRoots = list.data.roots as Root[]; setRoots(nextRoots); setActions(list.data.actions as Action[]); setRootId((current) => nextRoots.some((root) => root.id === current) ? current : nextRoots[0]?.id ?? ""); } if (status.ok) setCapabilities(status.data); }, [request, workspaceId]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 500); return () => window.clearInterval(timer); }, [load]);
  const loadFiles = useCallback(async () => { if (!rootId) { setFiles([]); return; } const result = await request("automation.listFiles", { rootId, path: "" }, workspaceId); if (result.ok) setFiles(result.data.entries as typeof files); else setMessage(result.error.message); }, [request, rootId, workspaceId]);
  useEffect(() => { void loadFiles(); }, [loadFiles]);
  const chooseRoot = async () => { const selected = await window.voidra?.shell.chooseDirectory(); if (selected?.path) setRootPath(selected.path); };
  const addRoot = async () => { const result = await request("automation.addRoot", { name: rootName, path: rootPath }, workspaceId); setMessage(result.ok ? "File root added to this workspace." : result.error.message); if (result.ok) { setRootPath(""); await load(); } };
  const prepareFile = async () => { const payload: Record<string, unknown> = { rootId, action: fileAction, source }; if (destination) payload.destination = destination; if (fileAction === "write") payload.content = content; const result = await request("automation.prepareFile", payload, workspaceId); setMessage(result.ok ? "File action prepared for exact review." : result.error.message); await load(); };
  const prepareNative = async () => { let target: Record<string, unknown>; try { target = JSON.parse(nativeTarget); } catch { setMessage("Native target must be valid JSON."); return; } const result = await request("automation.prepareNative", { operation: nativeOperation, target }, workspaceId); setMessage(result.ok ? "Native action prepared for exact review." : result.error.message); await load(); };
  return <section className="automation-stack">
    <article className="panel automation-card"><p className="card-label">CAPABILITY STATUS</p><div className="capability-grid">{Object.entries(capabilities).map(([name, value]) => <div key={name}><strong>{name}</strong><span>{String(value)}</span></div>)}</div><small>Accessibility and screen status are observations, not grants. This unsigned build does not claim native helper consent.</small><button className="danger-button" onClick={async () => { const result = await request("automation.takeover", {}, workspaceId); setMessage(result.ok ? "User takeover requested; queued desktop actions will stop." : result.error.message); await load(); }}>Take over desktop control</button></article>
    <div className="automation-grid">
      <article className="panel automation-card"><p className="card-label">SCOPED FILE ROOTS</p><label>Root name<input aria-label="Automation root name" value={rootName} onChange={(event) => setRootName(event.target.value)} /></label><button onClick={chooseRoot}>Choose automation folder</button><p className="path-message">{rootPath || "No folder selected."}</p><button onClick={addRoot} disabled={!rootName.trim() || !rootPath}>Add scoped root</button><label>Active root<select aria-label="Automation file root" value={rootId} onChange={(event) => setRootId(event.target.value)}><option value="">Choose root</option>{roots.map((root) => <option key={root.id} value={root.id}>{root.name}</option>)}</select></label><div className="compact-list" aria-label="Automation root files">{files.map((file) => <button key={file.path} onClick={() => setSource(file.path)}><span><strong>{file.name}</strong><small>{file.type}</small></span></button>)}</div></article>
      <article className="panel automation-card"><p className="card-label">FILE ACTION REVIEW</p><label>Action<select aria-label="File action" value={fileAction} onChange={(event) => setFileAction(event.target.value as typeof fileAction)}><option value="copy">Copy</option><option value="move">Move</option><option value="trash">Move to recoverable trash</option><option value="write">Create text file</option></select></label><label>{fileAction === "write" ? "Target path" : "Source path"}<input aria-label="File action source" value={source} onChange={(event) => setSource(event.target.value)} /></label>{(fileAction === "copy" || fileAction === "move") && <label>Destination path<input aria-label="File action destination" value={destination} onChange={(event) => setDestination(event.target.value)} /></label>}{fileAction === "write" && <label>Text content<textarea aria-label="File action content" value={content} onChange={(event) => setContent(event.target.value)} /></label>}<button onClick={prepareFile} disabled={!rootId || !source}>Prepare exact file action</button></article>
      <article className="panel automation-card"><p className="card-label">SUPPORTED MAC ACTION</p><label>Operation<select aria-label="Native operation" value={nativeOperation} onChange={(event) => setNativeOperation(event.target.value as typeof nativeOperation)}><option value="open-path">Open path</option><option value="open-app">Open named application</option><option value="inspect-target">Inspect accessible target</option><option value="activate-control">Activate inspected control</option></select></label><label>Exact target JSON<textarea aria-label="Native target" value={nativeTarget} onChange={(event) => setNativeTarget(event.target.value)} /></label><button onClick={prepareNative}>Prepare native action</button><small>Production open actions use Electron's narrow path/application APIs. Accessibility interactions require the future signed helper; deterministic tests never masquerade as OS permission.</small></article>
      <article className="panel automation-card action-history"><p className="card-label">ACTION JOURNAL</p><div className="compact-list" aria-label="Automation actions">{actions.map((action) => <div key={action.id}><span><strong>{action.kind} · {action.operation} · {action.state}</strong><small>{action.source}{action.destination ? ` → ${action.destination}` : ""}{action.error ? ` · ${action.error}` : ""}{action.result ? ` · ${JSON.stringify(action.result)}` : ""}</small></span>{action.state === "awaiting-approval" && <button className="primary compact" onClick={() => void request(action.kind === "file" ? "automation.approveFile" : "automation.approveNative", { actionId: action.id }, workspaceId).then(async (result) => { setMessage(result.ok ? `Action ${String(result.data.state).replaceAll("-", " ")}.` : result.error.message); await load(); await loadFiles(); })}>Approve exact action</button>}{action.kind === "file" && action.state === "completed" && action.undo && <button onClick={async () => { const result = await request("automation.undoFile", { actionId: action.id }, workspaceId); setMessage(result.ok ? "File action undone." : result.error.message); await load(); await loadFiles(); }}>Undo</button>}</div>)}</div></article>
    </div>{message && <p className="save-message" role="status">{message}</p>}
  </section>;
}
