"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { RequestService } from "@/components/service-types";

type LocalTask = { id: string; title: string; dueDate: string | null; optional: boolean; completed: boolean; sourceId: string };
type DailyPlan = { id: string; date: string; timezone: string; markdown: string; revision: string; sources: Array<{ id: string; kind: string; label: string }>; conflicts: string[] };
type McpConnection = { id: string; name: string; status: string; capabilities: { tools: Array<{ name?: string; title?: string; description?: string }> } };
function today(timezone: string) { return new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }

export function PlannerPanel({ workspaceId, request }: { workspaceId: string; request: RequestService }) {
  const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone, []);
  const [tasks, setTasks] = useState<LocalTask[]>([]);
  const [plans, setPlans] = useState<DailyPlan[]>([]);
  const [defaultRoutine, setDefaultRoutine] = useState<{ name: string; client: string } | null>(null);
  const [title, setTitle] = useState(""); const [dueDate, setDueDate] = useState(""); const [optional, setOptional] = useState(false);
  const [date, setDate] = useState(() => today(timezone)); const [zone, setZone] = useState(timezone);
  const [availabilityStart, setAvailabilityStart] = useState("09:00"); const [availabilityEnd, setAvailabilityEnd] = useState("17:00");
  const [events, setEvents] = useState("[]"); const [unavailable, setUnavailable] = useState("");
  const [sourceQuery, setSourceQuery] = useState(""); const [sourceResults, setSourceResults] = useState<Array<{ baseId: string; documentId: string; label: string }>>([]); const [selectedSources, setSelectedSources] = useState<Array<{ baseId: string; documentId: string; label: string }>>([]);
  const [model, setModel] = useState("openai/gpt-4.1-mini");
  const [calendarTools, setCalendarTools] = useState<Array<{ value: string; label: string }>>([]); const [calendarTool, setCalendarTool] = useState(""); const [calendarChanges, setCalendarChanges] = useState("[]"); const [calendarAction, setCalendarAction] = useState<{ id: string; tool: string; arguments: Record<string, unknown> } | null>(null);
  const [activePlan, setActivePlan] = useState<DailyPlan | null>(null); const [markdown, setMarkdown] = useState(""); const [message, setMessage] = useState("");

  const load = useCallback(async () => {
    const [result, mcpResult] = await Promise.all([request("planner.list", {}, workspaceId), request("mcp.list", {}, workspaceId)]);
    if (!result.ok) { setMessage(result.error.message); return; }
    setTasks((result.data.tasks as LocalTask[]) ?? []);
    const nextPlans = (result.data.plans as DailyPlan[]) ?? []; setPlans(nextPlans);
    setDefaultRoutine(result.data.defaultRoutine as { name: string; client: string });
    setActivePlan((current) => current ? nextPlans.find(({ id }) => id === current.id) ?? current : nextPlans.find((plan) => plan.date === date) ?? null);
    if (mcpResult.ok) {
      const tools = ((mcpResult.data.connections as McpConnection[]) ?? []).filter(({ status }) => status === "ready").flatMap((connection) => connection.capabilities.tools.filter(({ name }) => /calendar|event/i.test(name ?? "")).map((tool) => ({ value: `${connection.id}|${tool.name}`, label: `${connection.name} / ${tool.title ?? tool.name}` })));
      setCalendarTools(tools); setCalendarTool((current) => tools.some(({ value }) => value === current) ? current : tools[0]?.value ?? "");
    }
  }, [date, request, workspaceId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (activePlan) setMarkdown(activePlan.markdown); }, [activePlan]);

  const planningPayload = () => {
    const parsed: unknown = JSON.parse(events || "[]");
    if (!Array.isArray(parsed)) throw new Error("Calendar commitments must be a JSON array.");
    return { date, timezone: zone, availability: availabilityStart && availabilityEnd ? { start: availabilityStart, end: availabilityEnd } : null, events: parsed, unavailableSources: unavailable.split(",").map((value) => value.trim()).filter(Boolean), sources: selectedSources.map(({ baseId, documentId }) => ({ baseId, documentId })) };
  };
  const addTask = async () => { const result = await request("planner.task.add", { title, dueDate: dueDate || null, optional }, workspaceId); setMessage(result.ok ? "Local task added." : result.error.message); if (result.ok) { setTitle(""); setDueDate(""); setOptional(false); await load(); } };
  const generateLocal = async () => { try { const result = await request("planner.generateLocal", planningPayload(), workspaceId); if (!result.ok) { setMessage(result.error.message); return; } const plan = result.data as unknown as DailyPlan; setActivePlan(plan); setMarkdown(plan.markdown); setMessage("Local plan generated without a model or account."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid planning input."); } };
  const prepareManual = async () => { try { const result = await request("planner.prepareManual", planningPayload(), workspaceId); setMessage(result.ok ? "Manual Plan the Day handoff prepared in Jobs. The clipboard was not changed." : result.error.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid planning input."); } };
  const generateAutomatic = async () => { try { const result = await request("planner.generateAutomatic", { ...planningPayload(), model }, workspaceId); setMessage(result.ok ? "Automatic planning task started. Review its exact file action in Assistant." : result.error.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid planning input."); } };
  const reviewCalendar = async () => { try { if (!activePlan || !calendarTool) return; const parsed: unknown = JSON.parse(calendarChanges); if (!Array.isArray(parsed) || !parsed.length) throw new Error("Calendar changes must be a non-empty JSON array."); const [connectionId, name] = calendarTool.split("|"); const result = await request("mcp.prepareTool", { connectionId, name, arguments: { changes: parsed, idempotencyKey: `${activePlan.id}:${activePlan.revision}` } }, workspaceId); if (result.ok) { setCalendarAction(result.data as unknown as typeof calendarAction); setMessage("Exact calendar changes are ready for review. No external change has run."); } else setMessage(result.error.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid calendar changes."); } };

  return <div className="planner-stack">
    <article className="panel planner-card"><p className="card-label">LOCAL INPUTS</p><div className="inline-fields"><input aria-label="Local task title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Finish project outline" /><input aria-label="Local task due date" type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /><label className="checkbox-row"><input aria-label="Optional local task" type="checkbox" checked={optional} onChange={(event) => setOptional(event.target.checked)} /> Optional</label><button onClick={addTask} disabled={!title.trim()}>Add task</button></div><div className="compact-list" aria-label="Local planning tasks">{tasks.map((task) => <div key={task.id}><label className="checkbox-row"><input type="checkbox" checked={task.completed} onChange={async (event) => { await request("planner.task.update", { taskId: task.id, completed: event.target.checked }, workspaceId); await load(); }} /><span><strong>{task.title}</strong><small>{task.dueDate ? `Due ${task.dueDate}` : "No deadline"} · {task.optional ? "optional" : "priority"} · {task.sourceId}</small></span></label><button onClick={async () => { await request("planner.task.remove", { taskId: task.id }, workspaceId); await load(); }}>Remove</button></div>)}</div></article>
    <article className="panel planner-card"><p className="card-label">PLAN THE DAY</p><small>Default routine: {defaultRoutine?.name ?? "Loading…"} · manual destination {defaultRoutine?.client ?? "—"}. Planning never changes an external calendar.</small><div className="planner-grid"><label>Date<input aria-label="Plan date" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Timezone<input aria-label="Plan timezone" value={zone} onChange={(event) => setZone(event.target.value)} /></label><label>Available from<input aria-label="Availability start" type="time" value={availabilityStart} onChange={(event) => setAvailabilityStart(event.target.value)} /></label><label>Available until<input aria-label="Availability end" type="time" value={availabilityEnd} onChange={(event) => setAvailabilityEnd(event.target.value)} /></label></div><label>Calendar commitments JSON<textarea aria-label="Planning commitments" value={events} onChange={(event) => setEvents(event.target.value)} placeholder='[{"sourceId":"calendar:event-1","title":"Review","start":"2026-09-20T08:00:00.000Z","end":"2026-09-20T09:00:00.000Z"}]' /></label><label>Unavailable sources, comma separated<input aria-label="Unavailable planning sources" value={unavailable} onChange={(event) => setUnavailable(event.target.value)} placeholder="Work calendar" /></label><div className="inline-fields"><input aria-label="Planning source query" value={sourceQuery} onChange={(event) => setSourceQuery(event.target.value)} placeholder="Search workspace knowledge" /><button onClick={async () => { const result = await request("knowledge.search", { query: sourceQuery }, workspaceId); if (result.ok) setSourceResults(((result.data.results as Array<Record<string, unknown>>) ?? []).map((entry) => ({ baseId: String(entry.baseId), documentId: String(entry.id), label: `${String(entry.baseName)} / ${String(entry.path)}` }))); else setMessage(result.error.message); }}>Find planning sources</button></div><div className="compact-list" aria-label="Planning knowledge sources">{sourceResults.map((source) => { const selected = selectedSources.some((entry) => entry.baseId === source.baseId && entry.documentId === source.documentId); return <button key={`${source.baseId}:${source.documentId}`} className={selected ? "selected-source" : ""} onClick={() => setSelectedSources((current) => selected ? current.filter((entry) => entry.baseId !== source.baseId || entry.documentId !== source.documentId) : [...current, source])}>{selected ? "✓ " : "+ "}{source.label}</button>; })}</div><div className="button-row"><button className="primary" onClick={generateLocal}>Generate locally</button><button onClick={prepareManual}>Prepare Codex handoff</button></div><div className="inline-fields"><input aria-label="Planning model" value={model} onChange={(event) => setModel(event.target.value)} /><button onClick={generateAutomatic} disabled={!model.trim()}>Run automatic planner</button></div></article>
    {activePlan && <article className="panel planner-card"><p className="card-label">EDITABLE DAILY PLAN</p><label>Markdown<textarea className="plan-editor" aria-label="Daily plan Markdown" value={markdown} onChange={(event) => setMarkdown(event.target.value)} /></label><div className="button-row"><button className="primary" onClick={async () => { const result = await request("planner.save", { planId: activePlan.id, markdown, expectedRevision: activePlan.revision }, workspaceId); if (result.ok) { const plan = result.data as unknown as DailyPlan; setActivePlan(plan); setMessage("Daily plan saved to the workspace."); await load(); } else setMessage(result.error.message); }}>Save plan</button><select aria-label="Saved daily plans" value={activePlan.id} onChange={(event) => setActivePlan(plans.find(({ id }) => id === event.target.value) ?? null)}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.date}</option>)}</select></div><small>{activePlan.sources.length} sources · {activePlan.conflicts.length} unresolved conflict disclosures</small></article>}
    {activePlan && <article className="panel planner-card"><p className="card-label">APPLY TO CALENDAR</p><small>This is a separate reviewed MCP action. Planning alone never grants permission to create, move, invite, or delete calendar events.</small>{calendarTools.length ? <><label>Connected calendar tool<select aria-label="Calendar apply tool" value={calendarTool} onChange={(event) => setCalendarTool(event.target.value)}>{calendarTools.map((tool) => <option key={tool.value} value={tool.value}>{tool.label}</option>)}</select></label><label>Exact changes JSON<textarea aria-label="Calendar changes" value={calendarChanges} onChange={(event) => setCalendarChanges(event.target.value)} placeholder='[{"sourceId":"suggested:block-1","title":"Focus block","start":"2026-09-20T09:00:00.000Z","end":"2026-09-20T10:00:00.000Z"}]' /></label><button onClick={reviewCalendar}>Review calendar changes</button>{calendarAction && <div aria-label="Calendar change review"><pre>{JSON.stringify(calendarAction.arguments, null, 2)}</pre><button className="primary" onClick={async () => { const result = await request("mcp.approveTool", { actionId: calendarAction.id }, workspaceId); setMessage(result.ok ? `Calendar action ${String(result.data.state)}.` : result.error.message); if (result.ok) setCalendarAction(null); }}>Approve exact calendar changes</button></div>}</> : <p>No ready MCP tool with “calendar” or “event” in its name. Connect a supported provider in Settings; Q04's first live provider remains unselected.</p>}</article>}
    {message && <p className="save-message" role="status">{message}</p>}
  </div>;
}
